services:
  # 1. Database Service (MySQL)
  db:
    image: mysql:8.0
    container_name: antrian-mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sistem_antrian
      MYSQL_USER: antrian_user
      MYSQL_PASSWORD: PasswordKuatAnda123!
      MYSQL_ROOT_PASSWORD: RootPasswordKuat123!
    volumes:
      - dbdata:/var/lib/mysql

  # 2. Core Web App Service (Laravel / PHP-FPM)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: antrian-laravel
    restart: unless-stopped
    tty: true
    working_dir: /var/www/html
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  # 3. WebSocket Service (Node.js Socket.io)
  socket:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    container_name: antrian-socket
    restart: unless-stopped
    tty: true
    ports:
      - "3000:3000"

  # 4. Web Server Service (Nginx)
  web:
    image: nginx:alpine
    container_name: antrian-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
      - socket

volumes:
  dbdata:
    driver: local
